// src/components/Grumpus.tsx
import { useEffect, useRef, useState } from "react";
import "./Grumpus.css";

type Props = {
  img: string,
};

function Grumpus({ img }: Props) {
  const [i, setI] = useState(0);
  const audioRef = useRef<HTMLAudioElement>(null);

  useEffect(() => {
    const interval = setInterval(() => {
      setI((prevI) => (prevI + 1) % 3);
      if (!audioRef.current?.paused ?? false) {
          setI((prevI) => prevI + 3);
      }
    }, 100);

    return () => clearInterval(interval);
  }, []);

  const handleButtonClick = () => {
      audioRef.current?.play();
  };

  return (
    <>
      <button
        className="grumpus"
        style={{
          background: `url(${img})`,
          backgroundPositionX: -i * 128,
        }}
        onClick={handleButtonClick}
      />
      <audio src="/squee.wav" ref={audioRef}></audio>
    </>
  );
}

export default Grumpus;

// src/lib/Grumpus.svelte
<script lang="ts">
    import squee from '../assets/squee.wav';
    export let img: string;
    let audio = new Audio(squee);
    let i = 0;
    setInterval(() => {
        i = ((++i) % 3);
        if (!audio.paused)
            i += 3;
    }, 100);
</script>

<button class="grumpus" style="background: url({img}); background-position: {-i*128}px 0;" on:click={() => audio.play()}>
</button>

<style>
    .grumpus {
        width: 128px;
        height: 128px;
        border: 0px;
        outline: none;
        /* border: 1px solid white; */
    }
</style>
